# Generated by Django 5.1.6 on 2025-03-01 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_contact_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
